live_config_reload = true

[cursor]
style = "Beam"

[font]
size = 16.0

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "Regular"

[window]
dynamic_padding = false
opacity = 0.7
decorations = "Buttonless"
blur = true

[window.padding]
x = 4
y = 4


